# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Naomi Chan
email: dearnaomichan@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "naomichan.info" # the base hostname & protocol for your site, e.g. http://example.com
instagram: dearnaomichan
linkedin: https://www.linkedin.com/in/naomi-chan-34996439/
resume: https://drive.google.com/file/d/1I3CcRA0mDFzdM41vlUilt8S9GfI3KvfR/view?usp=sharing
marquee-about: Naomi chan Naomi chan Naomi chan Naomi chan
  # pretty good cook / loves to travel / binge watches cult documentaries / loves to camp in the fall / always down for a walking sport / always ready for a competitive game of Scrabble / obsessive list maker / could eat Dim Sum for the rest of her life / would be an astronaut in a different lifetime ~ loves working with passionate people ~

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
excerpt_separator: <!--more-->

# Home page info
updated: "updated: 2.28.18"
description: Currently working at MONO Creative Agency, Minneapolis MN.

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
